class PhoneCountryCode {
  const PhoneCountryCode({
    required this.code,
    required this.dialCode,
    required this.label,
    this.localMinLength = 4,
    this.localMaxLength = 15,
  });

  final String code;
  final String dialCode;
  final String label;
  final int localMinLength;
  final int localMaxLength;
}

const phoneCountryCodes = <PhoneCountryCode>[
  PhoneCountryCode(code: 'AF', dialCode: '+93', label: 'Afghanistan'),
  PhoneCountryCode(code: 'AL', dialCode: '+355', label: 'Albania'),
  PhoneCountryCode(code: 'DZ', dialCode: '+213', label: 'Algeria'),
  PhoneCountryCode(code: 'AS', dialCode: '+1684', label: 'American Samoa'),
  PhoneCountryCode(code: 'AD', dialCode: '+376', label: 'Andorra'),
  PhoneCountryCode(code: 'AO', dialCode: '+244', label: 'Angola'),
  PhoneCountryCode(code: 'AI', dialCode: '+1264', label: 'Anguilla'),
  PhoneCountryCode(code: 'AG', dialCode: '+1268', label: 'Antigua and Barbuda'),
  PhoneCountryCode(code: 'AR', dialCode: '+54', label: 'Argentina'),
  PhoneCountryCode(code: 'AM', dialCode: '+374', label: 'Armenia'),
  PhoneCountryCode(code: 'AW', dialCode: '+297', label: 'Aruba'),
  PhoneCountryCode(code: 'AU', dialCode: '+61', label: 'Australia'),
  PhoneCountryCode(code: 'AT', dialCode: '+43', label: 'Austria'),
  PhoneCountryCode(code: 'AZ', dialCode: '+994', label: 'Azerbaijan'),
  PhoneCountryCode(code: 'BS', dialCode: '+1242', label: 'Bahamas'),
  PhoneCountryCode(code: 'BH', dialCode: '+973', label: 'Bahrain'),
  PhoneCountryCode(code: 'BD', dialCode: '+880', label: 'Bangladesh'),
  PhoneCountryCode(code: 'BB', dialCode: '+1246', label: 'Barbados'),
  PhoneCountryCode(code: 'BY', dialCode: '+375', label: 'Belarus'),
  PhoneCountryCode(code: 'BE', dialCode: '+32', label: 'Belgium'),
  PhoneCountryCode(code: 'BZ', dialCode: '+501', label: 'Belize'),
  PhoneCountryCode(code: 'BJ', dialCode: '+229', label: 'Benin'),
  PhoneCountryCode(code: 'BM', dialCode: '+1441', label: 'Bermuda'),
  PhoneCountryCode(code: 'BT', dialCode: '+975', label: 'Bhutan'),
  PhoneCountryCode(code: 'BO', dialCode: '+591', label: 'Bolivia'),
  PhoneCountryCode(code: 'BA', dialCode: '+387', label: 'Bosnia and Herzegovina'),
  PhoneCountryCode(code: 'BW', dialCode: '+267', label: 'Botswana'),
  PhoneCountryCode(code: 'BR', dialCode: '+55', label: 'Brazil'),
  PhoneCountryCode(code: 'BN', dialCode: '+673', label: 'Brunei'),
  PhoneCountryCode(code: 'BG', dialCode: '+359', label: 'Bulgaria'),
  PhoneCountryCode(code: 'BF', dialCode: '+226', label: 'Burkina Faso'),
  PhoneCountryCode(code: 'BI', dialCode: '+257', label: 'Burundi'),
  PhoneCountryCode(code: 'KH', dialCode: '+855', label: 'Cambodia'),
  PhoneCountryCode(code: 'CM', dialCode: '+237', label: 'Cameroon'),
  PhoneCountryCode(code: 'CA', dialCode: '+1', label: 'Canada'),
  PhoneCountryCode(code: 'CV', dialCode: '+238', label: 'Cape Verde'),
  PhoneCountryCode(code: 'KY', dialCode: '+1345', label: 'Cayman Islands'),
  PhoneCountryCode(code: 'CF', dialCode: '+236', label: 'Central African Republic'),
  PhoneCountryCode(code: 'TD', dialCode: '+235', label: 'Chad'),
  PhoneCountryCode(code: 'CL', dialCode: '+56', label: 'Chile'),
  PhoneCountryCode(code: 'CN', dialCode: '+86', label: 'China'),
  PhoneCountryCode(code: 'CO', dialCode: '+57', label: 'Colombia'),
  PhoneCountryCode(code: 'KM', dialCode: '+269', label: 'Comoros'),
  PhoneCountryCode(code: 'CG', dialCode: '+242', label: 'Congo'),
  PhoneCountryCode(code: 'CD', dialCode: '+243', label: 'Congo (DRC)'),
  PhoneCountryCode(code: 'CR', dialCode: '+506', label: 'Costa Rica'),
  PhoneCountryCode(code: 'CI', dialCode: '+225', label: 'Cote d Ivoire'),
  PhoneCountryCode(code: 'HR', dialCode: '+385', label: 'Croatia'),
  PhoneCountryCode(code: 'CU', dialCode: '+53', label: 'Cuba'),
  PhoneCountryCode(code: 'CY', dialCode: '+357', label: 'Cyprus'),
  PhoneCountryCode(code: 'CZ', dialCode: '+420', label: 'Czech Republic'),
  PhoneCountryCode(code: 'DK', dialCode: '+45', label: 'Denmark'),
  PhoneCountryCode(code: 'DJ', dialCode: '+253', label: 'Djibouti'),
  PhoneCountryCode(code: 'DM', dialCode: '+1767', label: 'Dominica'),
  PhoneCountryCode(code: 'DO', dialCode: '+1809', label: 'Dominican Republic'),
  PhoneCountryCode(code: 'EC', dialCode: '+593', label: 'Ecuador'),
  PhoneCountryCode(code: 'EG', dialCode: '+20', label: 'Egypt'),
  PhoneCountryCode(code: 'SV', dialCode: '+503', label: 'El Salvador'),
  PhoneCountryCode(code: 'GQ', dialCode: '+240', label: 'Equatorial Guinea'),
  PhoneCountryCode(code: 'ER', dialCode: '+291', label: 'Eritrea'),
  PhoneCountryCode(code: 'EE', dialCode: '+372', label: 'Estonia'),
  PhoneCountryCode(code: 'SZ', dialCode: '+268', label: 'Eswatini'),
  PhoneCountryCode(code: 'ET', dialCode: '+251', label: 'Ethiopia'),
  PhoneCountryCode(code: 'FJ', dialCode: '+679', label: 'Fiji'),
  PhoneCountryCode(code: 'FI', dialCode: '+358', label: 'Finland'),
  PhoneCountryCode(code: 'FR', dialCode: '+33', label: 'France'),
  PhoneCountryCode(code: 'GF', dialCode: '+594', label: 'French Guiana'),
  PhoneCountryCode(code: 'PF', dialCode: '+689', label: 'French Polynesia'),
  PhoneCountryCode(code: 'GA', dialCode: '+241', label: 'Gabon'),
  PhoneCountryCode(code: 'GM', dialCode: '+220', label: 'Gambia'),
  PhoneCountryCode(code: 'GE', dialCode: '+995', label: 'Georgia'),
  PhoneCountryCode(code: 'DE', dialCode: '+49', label: 'Germany'),
  PhoneCountryCode(code: 'GH', dialCode: '+233', label: 'Ghana'),
  PhoneCountryCode(code: 'GR', dialCode: '+30', label: 'Greece'),
  PhoneCountryCode(code: 'GD', dialCode: '+1473', label: 'Grenada'),
  PhoneCountryCode(code: 'GP', dialCode: '+590', label: 'Guadeloupe'),
  PhoneCountryCode(code: 'GU', dialCode: '+1671', label: 'Guam'),
  PhoneCountryCode(code: 'GT', dialCode: '+502', label: 'Guatemala'),
  PhoneCountryCode(code: 'GN', dialCode: '+224', label: 'Guinea'),
  PhoneCountryCode(code: 'GW', dialCode: '+245', label: 'Guinea-Bissau'),
  PhoneCountryCode(code: 'GY', dialCode: '+592', label: 'Guyana'),
  PhoneCountryCode(code: 'HT', dialCode: '+509', label: 'Haiti'),
  PhoneCountryCode(code: 'HN', dialCode: '+504', label: 'Honduras'),
  PhoneCountryCode(code: 'HK', dialCode: '+852', label: 'Hong Kong'),
  PhoneCountryCode(code: 'HU', dialCode: '+36', label: 'Hungary'),
  PhoneCountryCode(code: 'IS', dialCode: '+354', label: 'Iceland'),
  PhoneCountryCode(code: 'IN', dialCode: '+91', label: 'India', localMinLength: 10, localMaxLength: 10),
  PhoneCountryCode(code: 'ID', dialCode: '+62', label: 'Indonesia'),
  PhoneCountryCode(code: 'IR', dialCode: '+98', label: 'Iran'),
  PhoneCountryCode(code: 'IQ', dialCode: '+964', label: 'Iraq'),
  PhoneCountryCode(code: 'IE', dialCode: '+353', label: 'Ireland'),
  PhoneCountryCode(code: 'IL', dialCode: '+972', label: 'Israel'),
  PhoneCountryCode(code: 'IT', dialCode: '+39', label: 'Italy'),
  PhoneCountryCode(code: 'JM', dialCode: '+1876', label: 'Jamaica'),
  PhoneCountryCode(code: 'JP', dialCode: '+81', label: 'Japan'),
  PhoneCountryCode(code: 'JO', dialCode: '+962', label: 'Jordan'),
  PhoneCountryCode(code: 'KZ', dialCode: '+7', label: 'Kazakhstan'),
  PhoneCountryCode(code: 'KE', dialCode: '+254', label: 'Kenya'),
  PhoneCountryCode(code: 'KI', dialCode: '+686', label: 'Kiribati'),
  PhoneCountryCode(code: 'KW', dialCode: '+965', label: 'Kuwait'),
  PhoneCountryCode(code: 'KG', dialCode: '+996', label: 'Kyrgyzstan'),
  PhoneCountryCode(code: 'LA', dialCode: '+856', label: 'Laos'),
  PhoneCountryCode(code: 'LV', dialCode: '+371', label: 'Latvia'),
  PhoneCountryCode(code: 'LB', dialCode: '+961', label: 'Lebanon'),
  PhoneCountryCode(code: 'LS', dialCode: '+266', label: 'Lesotho'),
  PhoneCountryCode(code: 'LR', dialCode: '+231', label: 'Liberia'),
  PhoneCountryCode(code: 'LY', dialCode: '+218', label: 'Libya'),
  PhoneCountryCode(code: 'LI', dialCode: '+423', label: 'Liechtenstein'),
  PhoneCountryCode(code: 'LT', dialCode: '+370', label: 'Lithuania'),
  PhoneCountryCode(code: 'LU', dialCode: '+352', label: 'Luxembourg'),
  PhoneCountryCode(code: 'MO', dialCode: '+853', label: 'Macau'),
  PhoneCountryCode(code: 'MG', dialCode: '+261', label: 'Madagascar'),
  PhoneCountryCode(code: 'MW', dialCode: '+265', label: 'Malawi'),
  PhoneCountryCode(code: 'MY', dialCode: '+60', label: 'Malaysia'),
  PhoneCountryCode(code: 'MV', dialCode: '+960', label: 'Maldives'),
  PhoneCountryCode(code: 'ML', dialCode: '+223', label: 'Mali'),
  PhoneCountryCode(code: 'MT', dialCode: '+356', label: 'Malta'),
  PhoneCountryCode(code: 'MH', dialCode: '+692', label: 'Marshall Islands'),
  PhoneCountryCode(code: 'MQ', dialCode: '+596', label: 'Martinique'),
  PhoneCountryCode(code: 'MR', dialCode: '+222', label: 'Mauritania'),
  PhoneCountryCode(code: 'MU', dialCode: '+230', label: 'Mauritius'),
  PhoneCountryCode(code: 'MX', dialCode: '+52', label: 'Mexico'),
  PhoneCountryCode(code: 'FM', dialCode: '+691', label: 'Micronesia'),
  PhoneCountryCode(code: 'MD', dialCode: '+373', label: 'Moldova'),
  PhoneCountryCode(code: 'MC', dialCode: '+377', label: 'Monaco'),
  PhoneCountryCode(code: 'MN', dialCode: '+976', label: 'Mongolia'),
  PhoneCountryCode(code: 'ME', dialCode: '+382', label: 'Montenegro'),
  PhoneCountryCode(code: 'MS', dialCode: '+1664', label: 'Montserrat'),
  PhoneCountryCode(code: 'MA', dialCode: '+212', label: 'Morocco'),
  PhoneCountryCode(code: 'MZ', dialCode: '+258', label: 'Mozambique'),
  PhoneCountryCode(code: 'MM', dialCode: '+95', label: 'Myanmar'),
  PhoneCountryCode(code: 'NA', dialCode: '+264', label: 'Namibia'),
  PhoneCountryCode(code: 'NR', dialCode: '+674', label: 'Nauru'),
  PhoneCountryCode(code: 'NP', dialCode: '+977', label: 'Nepal'),
  PhoneCountryCode(code: 'NL', dialCode: '+31', label: 'Netherlands'),
  PhoneCountryCode(code: 'NC', dialCode: '+687', label: 'New Caledonia'),
  PhoneCountryCode(code: 'NZ', dialCode: '+64', label: 'New Zealand'),
  PhoneCountryCode(code: 'NI', dialCode: '+505', label: 'Nicaragua'),
  PhoneCountryCode(code: 'NE', dialCode: '+227', label: 'Niger'),
  PhoneCountryCode(code: 'NG', dialCode: '+234', label: 'Nigeria'),
  PhoneCountryCode(code: 'MK', dialCode: '+389', label: 'North Macedonia'),
  PhoneCountryCode(code: 'NO', dialCode: '+47', label: 'Norway'),
  PhoneCountryCode(code: 'OM', dialCode: '+968', label: 'Oman'),
  PhoneCountryCode(code: 'PK', dialCode: '+92', label: 'Pakistan'),
  PhoneCountryCode(code: 'PW', dialCode: '+680', label: 'Palau'),
  PhoneCountryCode(code: 'PS', dialCode: '+970', label: 'Palestine'),
  PhoneCountryCode(code: 'PA', dialCode: '+507', label: 'Panama'),
  PhoneCountryCode(code: 'PG', dialCode: '+675', label: 'Papua New Guinea'),
  PhoneCountryCode(code: 'PY', dialCode: '+595', label: 'Paraguay'),
  PhoneCountryCode(code: 'PE', dialCode: '+51', label: 'Peru'),
  PhoneCountryCode(code: 'PH', dialCode: '+63', label: 'Philippines'),
  PhoneCountryCode(code: 'PL', dialCode: '+48', label: 'Poland'),
  PhoneCountryCode(code: 'PT', dialCode: '+351', label: 'Portugal'),
  PhoneCountryCode(code: 'PR', dialCode: '+1787', label: 'Puerto Rico'),
  PhoneCountryCode(code: 'QA', dialCode: '+974', label: 'Qatar'),
  PhoneCountryCode(code: 'RE', dialCode: '+262', label: 'Reunion'),
  PhoneCountryCode(code: 'RO', dialCode: '+40', label: 'Romania'),
  PhoneCountryCode(code: 'RU', dialCode: '+7', label: 'Russia'),
  PhoneCountryCode(code: 'RW', dialCode: '+250', label: 'Rwanda'),
  PhoneCountryCode(code: 'KN', dialCode: '+1869', label: 'Saint Kitts and Nevis'),
  PhoneCountryCode(code: 'LC', dialCode: '+1758', label: 'Saint Lucia'),
  PhoneCountryCode(code: 'VC', dialCode: '+1784', label: 'Saint Vincent and the Grenadines'),
  PhoneCountryCode(code: 'WS', dialCode: '+685', label: 'Samoa'),
  PhoneCountryCode(code: 'SM', dialCode: '+378', label: 'San Marino'),
  PhoneCountryCode(code: 'ST', dialCode: '+239', label: 'Sao Tome and Principe'),
  PhoneCountryCode(code: 'SA', dialCode: '+966', label: 'Saudi Arabia'),
  PhoneCountryCode(code: 'SN', dialCode: '+221', label: 'Senegal'),
  PhoneCountryCode(code: 'RS', dialCode: '+381', label: 'Serbia'),
  PhoneCountryCode(code: 'SC', dialCode: '+248', label: 'Seychelles'),
  PhoneCountryCode(code: 'SL', dialCode: '+232', label: 'Sierra Leone'),
  PhoneCountryCode(code: 'SG', dialCode: '+65', label: 'Singapore'),
  PhoneCountryCode(code: 'SK', dialCode: '+421', label: 'Slovakia'),
  PhoneCountryCode(code: 'SI', dialCode: '+386', label: 'Slovenia'),
  PhoneCountryCode(code: 'SB', dialCode: '+677', label: 'Solomon Islands'),
  PhoneCountryCode(code: 'SO', dialCode: '+252', label: 'Somalia'),
  PhoneCountryCode(code: 'ZA', dialCode: '+27', label: 'South Africa'),
  PhoneCountryCode(code: 'KR', dialCode: '+82', label: 'South Korea'),
  PhoneCountryCode(code: 'SS', dialCode: '+211', label: 'South Sudan'),
  PhoneCountryCode(code: 'ES', dialCode: '+34', label: 'Spain'),
  PhoneCountryCode(code: 'LK', dialCode: '+94', label: 'Sri Lanka'),
  PhoneCountryCode(code: 'SD', dialCode: '+249', label: 'Sudan'),
  PhoneCountryCode(code: 'SR', dialCode: '+597', label: 'Suriname'),
  PhoneCountryCode(code: 'SE', dialCode: '+46', label: 'Sweden'),
  PhoneCountryCode(code: 'CH', dialCode: '+41', label: 'Switzerland'),
  PhoneCountryCode(code: 'SY', dialCode: '+963', label: 'Syria'),
  PhoneCountryCode(code: 'TW', dialCode: '+886', label: 'Taiwan'),
  PhoneCountryCode(code: 'TJ', dialCode: '+992', label: 'Tajikistan'),
  PhoneCountryCode(code: 'TZ', dialCode: '+255', label: 'Tanzania'),
  PhoneCountryCode(code: 'TH', dialCode: '+66', label: 'Thailand'),
  PhoneCountryCode(code: 'TL', dialCode: '+670', label: 'Timor-Leste'),
  PhoneCountryCode(code: 'TG', dialCode: '+228', label: 'Togo'),
  PhoneCountryCode(code: 'TO', dialCode: '+676', label: 'Tonga'),
  PhoneCountryCode(code: 'TT', dialCode: '+1868', label: 'Trinidad and Tobago'),
  PhoneCountryCode(code: 'TN', dialCode: '+216', label: 'Tunisia'),
  PhoneCountryCode(code: 'TR', dialCode: '+90', label: 'Turkey'),
  PhoneCountryCode(code: 'TM', dialCode: '+993', label: 'Turkmenistan'),
  PhoneCountryCode(code: 'TC', dialCode: '+1649', label: 'Turks and Caicos Islands'),
  PhoneCountryCode(code: 'UG', dialCode: '+256', label: 'Uganda'),
  PhoneCountryCode(code: 'UA', dialCode: '+380', label: 'Ukraine'),
  PhoneCountryCode(code: 'AE', dialCode: '+971', label: 'United Arab Emirates'),
  PhoneCountryCode(code: 'GB', dialCode: '+44', label: 'United Kingdom'),
  PhoneCountryCode(code: 'US', dialCode: '+1', label: 'United States'),
  PhoneCountryCode(code: 'UY', dialCode: '+598', label: 'Uruguay'),
  PhoneCountryCode(code: 'UZ', dialCode: '+998', label: 'Uzbekistan'),
  PhoneCountryCode(code: 'VU', dialCode: '+678', label: 'Vanuatu'),
  PhoneCountryCode(code: 'VE', dialCode: '+58', label: 'Venezuela'),
  PhoneCountryCode(code: 'VN', dialCode: '+84', label: 'Vietnam'),
  PhoneCountryCode(code: 'VG', dialCode: '+1284', label: 'Virgin Islands (British)'),
  PhoneCountryCode(code: 'VI', dialCode: '+1340', label: 'Virgin Islands (US)'),
  PhoneCountryCode(code: 'YE', dialCode: '+967', label: 'Yemen'),
  PhoneCountryCode(code: 'ZM', dialCode: '+260', label: 'Zambia'),
  PhoneCountryCode(code: 'ZW', dialCode: '+263', label: 'Zimbabwe'),
];

PhoneCountryCode phoneCountryFromDialCode(String? dialCode) {
  final normalized = normalizeDialCode(dialCode);
  if (normalized == null) {
    return phoneCountryCodes.first;
  }
  return phoneCountryCodes.firstWhere(
    (country) => country.dialCode == normalized,
    orElse: () => PhoneCountryCode(
      code: 'XX',
      dialCode: normalized,
      label: 'International',
    ),
  );
}

PhoneCountryCode? findPhoneCountryByCode(String? code) {
  if (code == null || code.isEmpty) return null;
  final upper = code.toUpperCase();
  for (final country in phoneCountryCodes) {
    if (country.code == upper) return country;
  }
  return null;
}

String? normalizeDialCode(String? value) {
  if (value == null) return null;
  var raw = value.trim();
  if (raw.isEmpty) return null;
  if (!raw.startsWith('+')) raw = '+$raw';
  final digits = raw.substring(1).replaceAll(RegExp(r'\D'), '');
  if (digits.isEmpty || digits.length > 4) return null;
  return '+$digits';
}
